version: '3.6'
services:
  node:
    container_name: project_timer_node
    image: 'node:latest'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    links:
      - mongo
    networks:
      - timer-network
  mongo:
    container_name: project_timer_mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - timer-network
networks:
  timer-network:
    driver: bridge
